# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from grpc_proto import brain_pb2 as grpc__proto_dot_brain__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in grpc_proto/brain_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BrainServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ProcessDocument = channel.unary_unary(
                '/brain.BrainService/ProcessDocument',
                request_serializer=grpc__proto_dot_brain__pb2.DocumentRequest.SerializeToString,
                response_deserializer=grpc__proto_dot_brain__pb2.DocumentResponse.FromString,
                _registered_method=True)
        self.Chat = channel.unary_unary(
                '/brain.BrainService/Chat',
                request_serializer=grpc__proto_dot_brain__pb2.ChatRequest.SerializeToString,
                response_deserializer=grpc__proto_dot_brain__pb2.ChatResponse.FromString,
                _registered_method=True)
        self.ProcessNote = channel.unary_unary(
                '/brain.BrainService/ProcessNote',
                request_serializer=grpc__proto_dot_brain__pb2.NoteRequest.SerializeToString,
                response_deserializer=grpc__proto_dot_brain__pb2.DocumentResponse.FromString,
                _registered_method=True)


class BrainServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ProcessDocument(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Chat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessNote(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BrainServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ProcessDocument': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessDocument,
                    request_deserializer=grpc__proto_dot_brain__pb2.DocumentRequest.FromString,
                    response_serializer=grpc__proto_dot_brain__pb2.DocumentResponse.SerializeToString,
            ),
            'Chat': grpc.unary_unary_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=grpc__proto_dot_brain__pb2.ChatRequest.FromString,
                    response_serializer=grpc__proto_dot_brain__pb2.ChatResponse.SerializeToString,
            ),
            'ProcessNote': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessNote,
                    request_deserializer=grpc__proto_dot_brain__pb2.NoteRequest.FromString,
                    response_serializer=grpc__proto_dot_brain__pb2.DocumentResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'brain.BrainService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('brain.BrainService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BrainService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ProcessDocument(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.BrainService/ProcessDocument',
            grpc__proto_dot_brain__pb2.DocumentRequest.SerializeToString,
            grpc__proto_dot_brain__pb2.DocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.BrainService/Chat',
            grpc__proto_dot_brain__pb2.ChatRequest.SerializeToString,
            grpc__proto_dot_brain__pb2.ChatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessNote(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/brain.BrainService/ProcessNote',
            grpc__proto_dot_brain__pb2.NoteRequest.SerializeToString,
            grpc__proto_dot_brain__pb2.DocumentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
